# -*- coding: utf-8 -*-

import sys, os, argparse
import Image, struct, shutil

__version__ = "0.1.0"

def main (argv):
    parser = argparse.ArgumentParser(description="Converts a PNG file plus an APX+PAL generated by sixpack into a single APG file.")
    parser.add_argument("apg_file")
    parser.add_argument("png_file")
    parser.add_argument("apx_file")
    opts = parser.parse_args()

    with open (opts.apg_file, "wb") as out:
        def out_word(w):
            out.write(struct.pack('>H', w))

        img = Image.open(opts.png_file)
        (w, h) = img.size
        out_word(w)
        out_word(h)
        out_word(img.info['transparency'] if 'transparency' in img.info else 0xFFFF)

        pal_file = os.path.splitext(opts.apx_file)[0] + '.pal'
        pal_size = os.path.getsize(pal_file) / 2
        out_word(pal_size)

        with open(pal_file, "rb") as inp:
            shutil.copyfileobj(inp, out)

        with open(opts.apx_file, "rb") as inp:
            shutil.copyfileobj(inp, out)



#img = Image.open(r'C:\Users\Haroldo\Projetos\python\apg\test.png')
#newFile = open (r'C:\Users\Haroldo\Projetos\python\apg\test.apg', "wb")


if __name__ == '__main__':
    main(sys.argv)
